apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
spec:
  selector:
    app: my-daemonset
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: "TCP"
  type: NodePort
  externalTrafficPolicy: Local
