#!/bin/bash

# Default values

# IP addresses and port values
DEFAULT_SERVER_PORT=8080
DEFAULT_SERVER_IP=localhost

DEFAULT_CLIENT_SERVER_PORT_1=8081
DEFAULT_CLIENT_SERVER_PORT_2=8082
DEFAULT_CLIENT_SERVER_PORT_3=8083

DEFAULT_CLIENT_SERVER_IP_1=localhost
DEFAULT_CLIENT_SERVER_IP_2=localhost
DEFAULT_CLIENT_SERVER_IP_3=localhost

# Request and reporting periods
SERVER_REQUEST_PERIOD=5
CLIENT_SERVER_REPORTING_PERIOD_1=5
CLIENT_SERVER_REPORTING_PERIOD_2=5
CLIENT_SERVER_REPORTING_PERIOD_3=5
CLIENT_REPORTING_PERIOD_1=5
CLIENT_REPORTING_PERIOD_2=5
CLIENT_REPORTING_PERIOD_3=5
CLIENT_REPORTING_PERIOD_4=5
CLIENT_REPORTING_PERIOD_5=5
CLIENT_REPORTING_PERIOD_6=5
CLIENT_REPORTING_PERIOD_7=5
CLIENT_REPORTING_PERIOD_8=5
CLIENT_REPORTING_PERIOD_9=5
CLIENT_REPORTING_PERIOD_10=5
CLIENT_REPORTING_PERIOD_11=5
CLIENT_REPORTING_PERIOD_12=5

# Names
CLIENT_SERVER_NODE_NAME_1="RaspberryPi-1"
CLIENT_SERVER_NODE_NAME_2="RaspberryPi-2"
CLIENT_SERVER_NODE_NAME_3="RaspberryPi-3"
CLIENT_NODE_NAME_1="S-ESP32-1"
CLIENT_NODE_NAME_2="S-ESP32-2"
CLIENT_NODE_NAME_3="S-ESP32-3"
CLIENT_NODE_NAME_4="S-ESP32-4"
CLIENT_NODE_NAME_5="S-ESP32-5"
CLIENT_NODE_NAME_6="S-ESP32-6"
CLIENT_NODE_NAME_7="S-ESP32-7"
CLIENT_NODE_NAME_8="S-ESP32-8"
CLIENT_NODE_NAME_9="S-ESP32-9"
CLIENT_NODE_NAME_10="S-ESP32-10"
CLIENT_NODE_NAME_11="S-ESP32-11"
CLIENT_NODE_NAME_12="S-ESP32-12"

# Sensor list
SENSOR_LIST_1=./sensor-list/sensor-list.txt
SENSOR_LIST_2=./sensor-list/sensor-list.txt
SENSOR_LIST_3=./sensor-list/sensor-list.txt
SENSOR_LIST_4=./sensor-list/sensor-list.txt
SENSOR_LIST_5=./sensor-list/sensor-list.txt
SENSOR_LIST_6=./sensor-list/sensor-list.txt
SENSOR_LIST_7=./sensor-list/sensor-list.txt
SENSOR_LIST_8=./sensor-list/sensor-list.txt
SENSOR_LIST_9=./sensor-list/sensor-list.txt
SENSOR_LIST_10=./sensor-list/sensor-list.txt
SENSOR_LIST_11=./sensor-list/sensor-list.txt
SENSOR_LIST_12=./sensor-list/sensor-list.txt

# Network structure information
CLIENT_NUMBER=11
CLIENT_SERVER_NUMBER=3
CLIENTS_PER_CLIENT_SERVER=4

# Raspberry Pi OS link
RPI_OS_XZ_URL="https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2024-03-15/2024-03-15-raspios-bookworm-arm64-lite.img.xz"

