.PHONY: start-layers test-layers kill-layers

# Start layers on localhost
start-layers:
	./layer-control.sh "start-layers"

# Test layers on localhost
test-layers:
	./layer-control.sh "test-layers"

# Kill layers
kill-layers:
	./layer-control.sh "kill-layers"

